name: Running Script

on:
  schedule:
    - cron: '*/1 * * * *' 
  workflow_dispatch:

jobs:
  push_changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set Git Config
      run: |
        git config --global user.email "emjayfactor@gmail.com"
        git config --global user.name "mjfactor"

    
    - name: Replace Keywords
      run: |
        python script.py
        git add readme.md
        git commit -m "update"
        git push
